- .travis.yml
- WEB/FE/src/components/App.tsx
> [Common] travis test

- .travis.yml
- iOS/DaDaIkSeon/Podfile.lock
- TravisCI yml파일 수정
- Cocoapods 버전 수정
- yml 파일  확인해주세요
> [iOS] TravisCI yml파일 수정, Cocoapods 버전 수정

- WEB/BE/.eslintrc
- WEB/BE/.prettierrc
- WEB/BE/package-lock.json
- WEB/BE/package.json
- airbnb -> airbnb-base
- eslint-plugin-import 설치
- prettier 내용 FE와 동일하게 수정
close #55
> [BE] eslint, prettier 수정

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Main/Model/TOTPToken.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
- TOTP Token 모델 추가
- TOTPToken 모델 구조체에 더미 반환 함수 추가
- MainView에 더미 Array 추가
- 더미 Tokens로 ForEach를 사용하여 GridItem 표시
- TokenCewllView에 Binding 속성의 token 추가
- 그리드 아이템을 그릴 때, ForEach를 사용하였습니다. 하지만 아직 식별자를 어떻게 사용해야 하는지 잘 몰라서 index를 사용하여 더미 토큰 배열을 참조하였습니다.
> [iOS] TOTP Token 모델 추가 

- WEB/FE/.eslintrc.json
- WEB/FE/package-lock.json
- WEB/FE/package.json
- WEB/FE/src/style/globalStyle.ts
- WEB/FE/src/style/variable.ts
- WEB/FE/tsconfig.json
- Reset CSS를 만들어 GlobalStyle을 적용하였습니다.
- 사용하기로 결정한 Colos와 Font-size를 Enum으로 설정하였습니다.
- index.tsx render 코드를 React.StrictMode를 가장 상위 컴포넌트로 설정하고 그 아래 Global Style과 App을 뒀습니다.
- React.StrictMode의 장점
- 안전하지 않은 생명주기를 사용하는 컴포넌트 발견
- 레거시 문자열 ref 사용에 대한 경고
- 권장되지 않는 findDOMNode 사용에 대한 경고
- 예상치 못한 부작용 검사
- 레거시 context API 검사
- close #18
> [FE] GlobalStyle 적용

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainCellViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenListViewModel.swift
- 6자리 TOTP 비밀번호 표시
- Main Cell View 프로그레스 바 애니메이션
- ViewModel에 로직이 있습니다. 
- 그냥 현재 시간이 아니라, 오늘 0시 0분 0초를 기준으로 현재 시간입니다. 이 초를 30초로 모듈러 연산한 게 표시되어야 하는 시간입니다. 
- 아직 복사, 편집 버튼 동작은 구현하지 못한 상태입니다. 
- 시간의 마술사가 된 것 같네요🧙‍♀️ㅎㅎ
- close #issueNumber
> [iOS] Main Cell View 로직 구현

- WEB/BE/.eslintrc.json
- WEB/FE/.eslintrc.json
- WEB/FE/tsconfig.json
- WEB/FE/webpack.common.js
- tsconfig
- webpack
- eslint
- 위 3가지 수정
> [FE] path alias 설정

- WEB/FE/src/components/App.tsx
- WEB/FE/src/components/common/Modal.tsx
- WEB/FE/src/index.tsx
- WEB/FE/src/style/GlobalStyle.ts
- WEB/FE/src/style/theme.ts
- Modal 컴포넌트 추가
- 안에 들어가는 children, 스타일 객체인 style을 props로 받음
- Modal을 열고 닫는건 모달을 사용하는 컴포넌트에서 하도록 설계
```jsx
const Hello = () => (
<>
<Modal>
<div>Hi! I'm Modal</div>
</Modal>
</>
);
```
- close #24
> [FE]  Modal 컴포넌트 구현

- WEB/BE/controllers/auth/index.js
- WEB/BE/jsconfig.json
- WEB/BE/middlewares/validator.js
- WEB/BE/package.json
- WEB/BE/routes/auth/index.js
- WEB/BE/routes/user/index.js
- 회원가입,로그인 할 때 파라미터의 유효성을 검사하는 미들웨어 추가
- 현재 ID, PW만 구현
- 라우터에 미들웨어 추가해서 적용시킬 수 있음
> [BE] 회원가입,로그인 유효성 검사 미들웨어 추가

- WEB/BE/app.js
- WEB/BE/controllers/auth/index.js
- WEB/BE/controllers/user/index.js
- WEB/BE/jsconfig.json
- WEB/BE/middlewares/validator.js
- WEB/BE/package.json
- WEB/BE/routes/auth/index.js
- WEB/BE/routes/user/index.js
- WEB/BE/services/auth/index.js
- WEB/BE/utils/bcrypt/index.js
- id, pw를 검사한 후, 해당 유저가 있는지 체크
- 유저가 존재하지 않으면 400 에러 전달
- todo: 세션 생성하고 세션id 전달
- close #19
> [BE] login api 추가

- WEB/BE/app.js
- WEB/BE/controllers/user/index.js
- WEB/BE/models/redis/index.js
- WEB/BE/routes/user/index.js
- WEB/BE/services/auth/index.js
- WEB/BE/utils/bcrypt/index.js
- WEB/BE/utils/crypto/index.js
- WEB/FE/src/components/confirmEmail/index.tsx
> [BE,FE] fix: Eslint 변경에 따른 오류 수정

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon.xcworkspace/xcshareddata/swiftpm/Package.resolved
- iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainCellViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
- QR 가이브 뷰 추가
- QR 스캐너 추가 
- 메인 뷰를 네비게이션 뷰로 감싸주었습니다. 
- TokenAddView에 제스처를 추가해주었습니다. 
- 카메라 허용 문구를 plist에 추가했습니다. 
|![스크린샷 2020-11-26 오후 11 46 32](https://user-images.githubusercontent.com/44443949/100364531-9d992900-3041-11eb-89d3-518d8211d47c.png)|![스크린샷 2020-11-26 오후 11 46 42](https://user-images.githubusercontent.com/44443949/100364555-a427a080-3041-11eb-97bb-f8c253a219d0.png)|
|---|---|
- #28 
- #30 
- #46
> [iOS] QRCode 뷰 추가

- .travis.yml
> [BE] 2주차 배포

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Extensions/View+.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenViewModel.swift
- TokenEditView 전체적인 UI 구성
- 팔레트 추가하는 뷰 생성
- 아직 동작은 하지 않고 띄우기만 함.
- 토큰 입력을 할 때, 키보드 외 부분 터치하면 내려가게 함 << 근데 그 다음에  세그먼트가 클릭이 안됨. 수정필요
> [iOS] TokenEditView 생성

- WEB/BE/controllers/email/index.js
- WEB/BE/controllers/user/index.js
- Email 요청이 안가는 경우에 시간값이 변환되지 않는 문제 수정
- close #90
> [BE] 시간 값을 고정으로 두어서 API 요청 무시가 되는 경우 수정

- WEB/FE/src/components/common/Footer.tsx
- WEB/FE/src/components/common/Header.tsx
- WEB/FE/src/styles/theme.ts
- Header 컴포넌트 추가
- 로고, 로그인/로그아웃 버튼 등.. 을 나중에 추가
- Footer 컴포넌트 추가
- 깃허브 링크 같은것들을 추가할 수도?
> [FE] Header, Footer 컴포넌트 추가

- WEB/BE/controllers/auth/index.js
- WEB/BE/middlewares/reCAPTCHA.js
- WEB/BE/routes/auth/index.js
- WEB/BE/services/auth/index.js
- WEB/FE/src/api/index.tsx
- WEB/FE/src/components/App.tsx
- WEB/FE/src/components/LogIn/LogInForm.tsx
- WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
- WEB/FE/src/components/common/AuthForm.tsx
- WEB/FE/src/components/common/Button.tsx
- WEB/FE/src/components/common/Input.tsx
- WEB/FE/src/pages/LogInPage.tsx
- WEB/FE/src/pages/index.tsx
- WEB/FE/src/styles/GlobalStyle.ts
- FE 로그인 api 추가
- BE 로그인 api 수정
- comparePassword 사용하도록 수정
- saltRound ?
- 로그인 폼 관련 컴포넌트 추가
- AuthForm
- LogInPage
- LogInForm
- 로그인/회원가입 폼에서 재사용할 수 있는 부분을 따로 AuthForm으로 구현
- Input 컴포넌트 수정해서 적용 필요
> [FE] login form 추가, login api 수정

- WEB/BE/app.js
- WEB/BE/middlewares/sessionAuthentication.js
- WEB/BE/models/redis/index.js
- WEB/BE/package-lock.json
- WEB/BE/package.json
결국 컴터는 못살려서 다시 작성
- 로그인 api 성공 시, redis에 세션 정보 추가
- close #21
> [BE] session 추가

- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView+SubViews.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
> [iOS] 충돌 해결 Final

- WEB/BE/controllers/email/index.js
- WEB/BE/controllers/user/index.js
- WEB/BE/routes/user/index.js
- WEB/BE/services/user/index.js
- WEB/BE/utils/email/index.js
- 입력된 Email, 이름, 생년월일이 일치하는지 확인해야한다.
- 일치한다면 사용자의 Email로 사용자의 아이디를 보낼 수 있어야한다.
- Email controller 리펙토링 및 로직 추가 (WEB/BE/controllers/email/index.js)
- Email, 이름, 생일을 통해 id 값 가져오기 (WEB/BE/services/user/index.js)
- Email 계정 변경 =>  'dadaikseon@naver.com'
- close #111
> [BE] 아이디 찾기

- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/ZeroTokenView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
- Main화면으로 돌아왔을 때 refresh 기능 추가
- ZeroTokenMode일 떄 화면 수정, 다시 돌아올 수 있도록 수정
- NavigationView가 아니라 VStack에 onAppear 추가
- 토큰 0개에서 추가했을 때 ZeroTokenMode = false 추가
> [iOS] 추가/삭제 기능 머지 후 필요한 코드 추가

- WEB/BE/app.js
- WEB/BE/controllers/auth/index.js
- WEB/BE/middlewares/sessionAuthentication.js
- 로그인시 session 생성
- 미들웨어 추가로 필요시 사용
- 필요한 key 값 고려
**주의 사항**
- 아이디 비밀번호만 검증하고 생성됨 OTP로그인 완료 이후에 session 생성 위치 변경 필요
> [BE] session login시 연결

- WEB/BE/controllers/auth/index.js
- WEB/BE/package.json
- WEB/BE/services/auth/index.js
- WEB/BE/services/user/index.js
- WEB/BE/utils/email/index.js
- 인증 완료시 E-mail 전송
- Email param 으로 id & time 값 전송
- 인증 주소 /findPassword
- param 암호화 된 값으로 바꾸는 비밀번호와 함께 BE으로 전달
**생각 하는 방식**
1. Email 인증 링크 전달 (param 에 id & 만료시간 포함)
2. findPassword 에서 비밀번호 변경 body 와 함께 param 으로 전달
3. 만료 시간 사용자 검증 진행 이후 변경 성공 여부 전달
그런데 저렇게 하면 Param 없이 접근을 못하게 해야하나..?
- close #115
> [BE] 비밀번호 찾기 이메일 전송 함수 구현

- WEB/BE/controllers/auth/index.js
- WEB/BE/middlewares/verifyJWT.js
- WEB/BE/routes/auth/index.js
- WEB/BE/utils/totp/index.js
- 6자리를 검증하는 미들웨어를 구현하였습니다.
- TOTP 모듈을 적용하였습니다.
- close #25
> [BE] TOTP 6자리 검증 API 및 미들웨어 구현

- WEB/BE/controllers/auth/index.js
- WEB/BE/routes/auth/index.js
- WEB/BE/services/auth/index.js
- 비밀번호를 Verify해야한다.
- 비밀번호가 올바르게 입력됐을 때는 Auth의 비밀번호를 변경한다.
-
- close #114
> [BE] 비밀번호 찾기- 변경된 비밀번호 전송 API

- WEB/BE/utils/email/index.js
- file path 변경에 따른 endpoint 변경
> [BE] Email path 변경

- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
> [iOS] 버그들 수정

- WEB/FE/src/api/index.tsx
- api 부분에 사라진 코드를 복구하여 에러를 수정하였습니다.
- close #issueNumber
> [FE]: 에러 수정

- .github/workflows/FE.deploy.yml
- WEB/FE/src/components/App.tsx
> [FE] github action 배포

- WEB/FE/src/components/App.tsx
> [FE] 배포 테스트

- .github/workflows/BE.deploy.yml
- .github/workflows/FE.deploy.yml
- WEB/FE/src/components/App.tsx
> [BE] github actions 배포 테스트

- .github/workflows/BE.deploy.yml
- WEB/BE/app.js
> [BE] 배포 테스트

- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift
- 서치바 버그 수정
- 취소 버튼을 눌렀을 때 메인으로 나가려고 하는 함수와 search("")함수가 같이 불려서 꼬이는 버그가 있었다.
- TextFielddml editing을 감지하는 함수를 따로 두고, search함수를 불러올 때 false면 서치하지 않게 함.
- searchBarView 함수들 정리
- MainViewModel 함수들 정리
> [iOS] 서치바 버그 수정

- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
- 네비게이션 링크로 화면전환 시에도 타이머 On/Off 추가
> [iOS] 네비게이션 링크로 화면전환 시에도 타이머 On/Off

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Common/StorageManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/Model/Token.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/HeaderView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
- 키체인 붙이기
- Token 로드, 수정 키체인 붙임
- Token들이 앱을 지웠다 깔아도 남아있음.
- Update 함수는 없앰. 어차피 다시 저장하는것이기 때문에 deleteAll 후 다시 store 함.
- closes #174
> [iOS] 키체인 붙이기 

- iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
- iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/MockTokenService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenServiceable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView+SubViews.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenCellViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenEditViewModel.swift
- Token을 수정할 수 있게 됐어요.
- Token 수정 로직 추가
- Button 중복되는거 하나로 빼기
- refresh Action 추가 (갓재명,,,?)
> [iOS] Token 수정하기

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/MainView/Usecase/MainUsecase.swift
- iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/HeaderView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/MainView/View/SearchBarView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/MainView/ViewModel/CellHandler.swift
- iOS/DaDaIkSeon/DaDaIkSeon/MainView/ViewModel/CheckBoxHandler.swift
- iOS/DaDaIkSeon/DaDaIkSeon/MainView/ViewModel/Handlerable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/MainView/ViewModel/MainViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/MainView/ViewModel/SearchHandler.swift
- MainViewModel input 분리
- Input Handler로 input 처리 로직 분리
> [iOS] 메인 뷰모델 정리

- WEB/BE/controllers/auth/index.js
- WEB/FE/src/api/index.tsx
- WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
- api 함수 내에 try catch 제거
- 사용하는 컴포넌트에서 에러 처리하도록 수정
- 코드 형식 통일
- 로그인 api response type 추가
> [FE] api 리팩토링

- WEB/BE/controllers/auth/index.js
- WEB/BE/services/auth/index.js
- WEB/BE/utils/emailSender/index.js
- Secret Key 생성
- Email 템플릿 연결
- DB 생성된 Key로 변경
- close #106
> [BE] TOTP 재발급 새로운 Key 생성

- WEB/FE/src/components/App.tsx
- WEB/FE/src/components/MyPage/MyPageContainer.tsx
- WEB/FE/src/components/PrivateRoute/PrivateRoute.tsx
- WEB/FE/src/layouts/MainPageLayout.tsx
- WEB/FE/src/pages/MyPage.tsx
- WEB/FE/src/pages/NotFoundPage.tsx
- WEB/FE/src/pages/index.tsx
- MyPage, MyPageContainer 컴포넌트 추가
- react-tabs 사용
- PrivateRoute로 설정
- `/me` 로 url 설정
- MainPageLayout 수정
> [FE] MyPage 컴포넌트

- WEB/FE/src/components/MyPage/AccessLog.tsx
- WEB/FE/src/components/common/Table.tsx
- 접속 내역을 보여주는 AccessLog 컴포넌트 추가
- 테이블 컴포넌트 추가
- 테이블 컴포넌트에는 column, dataSource 를 넣어서 만들어주면 됩니다
```jsx
const columns = [
{ title: '시간', key: 'time' },
{ title: '디바이스', key: 'device' },
{ title: 'IP', key: 'ip' },
{ title: '위치', key: 'location' },
{
title: '상태',
key: 'isLoggedIn',
render: (isLoggedIn: boolean) => (isLoggedIn ? '로그인' : '로그아웃'),
},
{
title: '접속차단',
key: 'sessionId',
render: (sid: string) => (sid ? <Button text='로그아웃' onClick={() => console.log(sid)} /> : '-'),
},
];
const data = [
{
key: '0',
time: '2020-20-10',
device: 'iPhone',
ip: '201.2.1.3',
location: '서울',
isLoggedIn: false,
sessionId: undefined,
},
{
key: '1',
time: '2020-20-11',
device: 'Mac',
ip: '201.2.1.4',
location: '서울',
isLoggedIn: false,
sessionId: undefined,
},
{
key: '2',
time: '2020-20-12',
device: 'Window …
```
> [FE] AccessLog, Table 컴포넌트

- WEB/BE/controllers/auth/index.js
- WEB/BE/services/auth/index.js
- WEB/FE/src/api/index.tsx
- WEB/FE/src/components/LogIn/LogInContainer.tsx
- WEB/FE/src/components/PasswordModal/PasswordModal.tsx
- WEB/FE/src/components/TOTPModal/TOTPModal.tsx
- WEB/FE/src/utils/message.ts
- 패스워드를 입력할 수 있는 모달을 구현하였습니다.
- 패스워드를 전달할 수 있는 API를 구현하였습니다.
- 패스워드를 변경할 때 필요한 ID는 세션을 참고하는 것으로 수정하였습니다.
- close #196
> [FE] 내정보 변경을 위한 패스워드 입력 모달 구현

- WEB/BE/models/WEB/AUTHS.js
- WEB/BE/models/WEB/LOGS.js
- WEB/BE/models/WEB/USERS.js
- WEB/BE/seeders/dummyDataWEB.js
> [BE] Log model 변경

- WEB/FE/src/api/index.tsx
- WEB/FE/src/components/MyPage/MyPageContainer.tsx
- 조회, 수정하는 api 추가
- MyPageContainer에서 사용
> [FE] 내정보 조회, 수정 api 적용

- WEB/BE/controllers/user/index.js
- WEB/BE/middlewares/sessionAuthentication.js
- WEB/BE/routes/user/index.js
- WEB/BE/services/auth/index.js
- WEB/BE/services/user/index.js
- 내정보 조회, 수정에 사용되는 getUser, updateUser 컨트롤러 추가
- GET /api/user : getUser 
- PATCH /api/user : updateUser
- sessionCheck 다음에 오도록 배치
- 서비스 함수 수정
- authService.getUserById : user 전체 반환하도록 수정
> [BE] 내 정보 조회, 수정 API 추가

- WEB/BE/controllers/auth/index.js
- WEB/BE/package-lock.json
- WEB/BE/package.json
- WEB/BE/routes/auth/index.js
- WEB/BE/services/log/index.js
- 내정보를 변경하기 위해 비밀번호를 입력하는데, 이 때 비밀번호를 확인하기 위한 API를 생성하였습니다.
- 로그인시에 매번 Log를 남겨야하기 때문에 Log Table에 필요한 인자들을 넣어 Log 기록을 남기도록 하였습니다.
- close #198 , #205
> [BE] 비밀번호 확인 API, 접속기록 추가

- WEB/BE/controllers/auth/index.js
- WEB/BE/controllers/user/index.js
- WEB/BE/middlewares/sessionAuthentication.js
- WEB/BE/services/auth/index.js
- session.key -> session.user 사용하도록 수정
- try/catch 제거
- 코드 순서 정리
> [BE] 내정보 조회, 수정 api 수정, 리팩토링

- WEB/FE/src/components/MyPage/MyPageContainer.tsx
- WEB/FE/src/components/PasswordModal/PasswordModal.tsx
- MyPage에 수정 버튼을 눌렀을 때 Check Password Modal을 적용하였습니다.
- 비밀번호 확인 후에 수정이 가능합니다.
- close #196
> [FE] MyPage에 Check Password Modal 적용

- WEB/BE/app.js
- WEB/BE/controllers/log/index.js
- WEB/BE/middlewares/sessionAuthentication.js
- WEB/BE/models/redis/index.js
- WEB/BE/routes/log/index.js
- redis 리펙토링 (이벤트 리슨하는 인스턴스를 독립적으로 둠)
- log API 라우터 추가
- /api/log/session delete 로 원하는 session 삭제 가능
- session 관련 요청시마다 session 갱신
삭제하는 부분 핵심 로직
``` javascript
const logController = {
delSession(req, res, next) {
const { sid } = req.body;
const client = redis.client();
client.del(sid);
logService.update({ sid, isLoggedOut: true });
res.json({ result: true });
},
};
```
갱신하는 방법
``` javascript
req.session.touch();
```
- close #199
> [BE] 접속 디바이스 만료 - 사용자 요청에 의해 만료

- WEB/FE/.eslintrc.json
- WEB/FE/src/components/MyPage/MyPageContainer.tsx
> [FE] 마이페이지 에러 핸들링 추가

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Image+.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/QRGuideView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/ZeroTokenView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/PinCodeView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
- 핀코드뷰 유아이 개발
- 앱 번들아이디 변경
- 아직 유아이만 개발된 상태
- 앱의 번들아이디를 kr.codesquad.DaDaIkSeon으로 변경
- SettingView.swit 파일 고쳐서 충돌날 수도 있음.
> [iOS] PinCodeView UI 개발

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
- 파일 참조 경로 버그 fix
- 파일을 다시 참조할수 있게 build phase 의 compile sources에서 지웠다가 다시 넣어줌.
> [iOS] fix: File Reference Bug 고침

- WEB/BE/controllers/log/index.js
- WEB/BE/models/WEB/LOGS.js
- WEB/BE/routes/log/index.js
- WEB/BE/services/log/index.js
- WEB/FE/src/api/index.tsx
- WEB/FE/src/components/MyPage/AccessLog.tsx
- WEB/FE/src/components/MyPage/MyPageContainer.tsx
- 비동기 오류에 대한 처리 추가
- 만료시 SID 를 지워 주는 방식으로 구현
- Swagger  추가
- onClick 메소드 추가
중요 로직 ( 사실 이것만 보면 코드리뷰 끝 )
``` javascript
const onDelete = (sid: string) => {
if (delSession({ sid })) {
let newLogs = [...logs];
newLogs = newLogs.map((log: Log) => {
if (log.sessionId === sid) {
log.sessionId = '';
log.isLoggedIn = true;
}
return log;
});
setLogs(newLogs);
alert('로그아웃 성공');
return;
}
alert('요청 실패');
};
``` 
- close #197 
- close #230 
- close #229
> [FE][BE] 사용자에 의한 session 만료

- WEB/FE/src/components/MyPage/AccessLog.tsx
- 시간 출력 형식 변경
- 형식 2개중 하나 선택 필요
- close #237
> [FE] ChangeTimeView

- WEB/FE/src/components/App.tsx
- WEB/FE/src/components/IndexPage/Banner.tsx
- WEB/FE/src/components/IndexPage/IndexPageContainer.tsx
- WEB/FE/src/components/MyPage/MyPageContainer.tsx
- WEB/FE/src/components/PasswordModal/PasswordModal.tsx
- WEB/FE/src/components/common/Section/HeadingSection.tsx
- WEB/FE/src/pages/IndexPage.tsx
- WEB/FE/src/pages/MyPage.tsx
- WEB/FE/src/pages/QRCodePage.tsx
- WEB/FE/src/pages/index.tsx
- WEB/FE/src/utils/localStorage.ts
- IndexPage 컴포넌트 추가
- `/` 경로에서 렌더링될 페이지
- HeadingSection 컴포넌트 추가
- 각 페이지의 제목 부분에서 사용하려고 만듬
- 마이페이지에 적용했습니다
- 불필요한 코드 삭제
> [FE] IndexPage 컴포넌트 추가, HeadingSection 컴포넌트 구현

- WEB/BE/controllers/iOS/token/index.js
- WEB/BE/routes/iOS/index.js
- WEB/BE/routes/iOS/token/index.js
- WEB/BE/services/iOS/token/index.js
- WEB/BE/services/iOS/user/index.js
|URL|Method|Description|구현 여부|
|---|---|---|---|
|/|get|토큰 리스트|O|
|/|put|싱크 맞추기|X|
|/|post|토큰 추가|O|
|/:id|patch|토큰 수정|O|
|/:id|delete|토큰 삭제|O|
- close #242
> [BE] iOS Token CRUD Router, Controller, Service 구현하기

- WEB/BE/controllers/iOS/token/index.js
> [BE] fix: 콘솔 출력 삭제 및 변수 오타 수정

- WEB/BE/controllers/web/auth/index.js
- 이메일 인증을 하지 않았을 때 로그인할 수 없게 체크하였습니다.
```javascript
if (!user.is_verified) return next(createError(400, '이메일 인증이 필요합니다.'));
```
- close #260
> [BE]이메일 인증 체크 구현

- WEB/BE/controllers/iOS/user/index.js
- WEB/BE/utils/emailSender/index.js
- WEB/BE/utils/random/index.js
- 인증 6자리 번호를 생성하였습니다.
- 6자리를 사용자의 이메일로 전송하였습니다.
```javascript
async sendiOSEmailCode({ email, emailCode }) {
/** @TODO option 수정 필요 */
const axiosOptions = makeOption(1000, email, '', { emailCode });
try {
await axios(axiosOptions);
} catch (e) {
throw new Error(e);
}
},
```
템플릿 번호를 받아서 수정해야합니다 !
- close #261
> [BE] iOS 인증 6자리 생성 및 이메일 전송

- WEB/BE/controllers/web/auth/index.js
- WEB/BE/models/redis/index.js
- redis del 이벤트 추가 수신
- redis del 이벤트 작동 조건 ` req.session ` 추가
- close #259
> [BE] redis event 수신

- WEB/BE/config/swagger.js
- WEB/BE/controllers/iOS/token/index.js
- WEB/BE/routes/iOS/token/index.js
- WEB/BE/services/iOS/token/index.js
- WEB/BE/services/iOS/user/index.js
- 기존 토큰 삭제 API
- 받은 토큰 전부 추가 API
- 받은 시간으로 업데이트 하는 API 를 순차적으로 진행
- 트랜젝션 설정을 꼭 해야할듯 함
- close #245
> [BE] iOS 토큰API (Sync 맞추기)

- iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Image+.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/View/TokenCellView+SubViews.swift
-  inactive 배경을 로그인 배경 + 로고로 변경
- 프로그레스바 채워지는 방식에서 없어지는 방식으로 변경
> [iOS] inactive 배경 설정, 프로그레스바 반대 방향으로 변경

- WEB/BE/controllers/iOS/user/index.js
- WEB/BE/models/iOS/DEVICES.js
- WEB/BE/models/iOS/USERS.js
- 모델 수정
- multi_device, backup 기본값 true로 수정
- 이메일 전송 api 수정
- 유저가 있는 경우, 이메일 코드 갱신되도록 수정
- 이메일코드 인증 api 응답 수정
- 유저 정보 삭제
> [BE] iOS Model, API 수정

- WEB/BE/config/swagger.js
- WEB/BE/routes/iOS/user/index.js
> [BE] app/user swagger 문서 작성

- WEB/BE/controllers/iOS/token/index.js
- WEB/BE/routes/iOS/token/index.js
- Swagger iOS/Token 작성
- http://seokam.asuscomm.com:3000/api-docs/#/ 
- 개인 컴터 포트열어둔거인데 제 컴터를 하루종일 켜두는건 아니라서... 안들어가질 수 있습니다.
- close #274
> [BE] Swagger iOS/Token 작성

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/String+.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Common/Util/KeboardModifier.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Model/Device.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/HeaderView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView+Views/SettingView+BackupSetting.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView+Views/SettingView+DeviceSetting.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView+Views/SettingView+MyInfoSetting.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingViewComponents/SettingErrorMessageView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingViewComponents/SettingViewWrapper.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+Backup.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+MultiDevice.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
- SettingView UX/UI 정리 
- TimeStringToDate 추가 
- 에러 메세지 추가
- close #284
> [iOS] SettingView 정리

- iOS/DaDaIkSeon/.swiftlint.yml
- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Common/AppDelegate.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Common/Info.plist
- iOS/DaDaIkSeon/DaDaIkSeon/Common/JWTTokenStoreManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Common/Views/BackgroundView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/NetworkResult.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/User/JWTNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/Usecase/LoginUsecase.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginCodeView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/ViewModel/LoginViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/PinCodeView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Login/LoginService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
- 로그인 + 메인
- 로그인 에서 메인 넘어갈때 클로저로 넘겨주기
- 로그인시 JWT 토큰 키체인에 저장
- 앱 삭제하고 재 설치시 키체인 refresh
- AppDelegate didFinishLaunching에 작성
- 근데 이런 경고문이 뜨지만 해결 못함 ( 그냥 린트문제였음 )
- Lint에서 appdelegate 함수 이름이 길다는 경고를 띄워서 AppDelegate 파일 제외시켜줌
- Login 코드입력 실패시 alert 넣어줌
- codeView넘어갔을때, 이메일 확인하러 다른 앱 켰다가 돌아오면 다시 emailView로 넘어감
- UserDefaults로 확인해서 bool값 바꿔줌
- close #issueNumber
> [iOS] 로그인과 메인 합치기

- WEB/BE/config/swagger.js
- WEB/BE/routes/iOS/token/index.js
- WEB/BE/routes/iOS/user/index.js
- WEB/BE/routes/web/auth/index.js
- WEB/BE/routes/web/log/index.js
- WEB/BE/routes/web/user/index.js
- WEB/BE/services/iOS/token/index.js
- session 인증 방법 추가
- user 태그 값이 log 태그에 있어 수정
- 필요 인증 방식 추가 및 tag 설명 추가
- [Swagger 링크](http://seokam.asuscomm.com:3000/api-docs/#/) 참조
> [BE] Swagger session 인증 방법 추가

- WEB/BE/controllers/iOS/user/index.js
- WEB/BE/routes/iOS/user/index.js
- GET /api/app/user 추가
- 이메일 전송, 인증코드검증 컨트롤러 수정
- swagger 문서 수정
> [BE] iOS api 추가 및 수정

- WEB/BE/controllers/iOS/token/index.js
- WEB/BE/routes/iOS/token/index.js
- WEB/BE/services/iOS/token/index.js
- 파라미터 오류가 있는 부분을 수정하였고 테스트하였습니다.
> [BE] iOS token API swagger 파라미터 오류 수정

- WEB/BE/controllers/iOS/device/index.js
- WEB/BE/controllers/iOS/user/index.js
- WEB/BE/routes/iOS/user/index.js
- iOS api 수정
- 응답 전부 message로 수정
- swagger 문서 작성
> [BE] iOS api 수정

- WEB/BE/controllers/web/auth/index.js
- WEB/BE/controllers/web/user/index.js
- WEB/BE/routes/web/user/index.js
- Email 재전송 API 구현
- Swagger 추가
- close #272
> [BE] Email 재전송 추가

- WEB/FE/src/api/index.ts
- WEB/FE/src/components/LogIn/LogInContainer.tsx
- WEB/FE/src/components/LogIn/LogInForm.tsx
> [FE] Email 재전송 추가

- WEB/BE/utils/totp/index.js
- 30초 이전 값을 넣어도 성공하게 변경
- close #307
> [BE] 한스탭 앞 OTP 정보도 사용 가능

- WEB/BE/controllers/iOS/user/index.js
> [FE] iOS API 수정

- WEB/BE/controllers/iOS/user/index.js
- WEB/BE/utils/totp/hmac.js
- hmac 유틸 추가
- createHmac 함수
- 함수형 프로그래밍을 적용해 봤습니다
- 유틸함수만 추가하고 아직 적용은 안됐습니다
- 테스트 후 적용하면 될 듯..
> [BE] HMAC 생성 구현

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/Requestable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserEndpoint.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/Usecase/BackupPasswordUsecase.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/View/BackupPasswordView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/ViewModel/BackupPaswordViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/Usecase/LoginNetworkResult.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/Usecase/LoginUsecase.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginCodeView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/ViewModel/LoginViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/Usecase/MainUsecase.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/MainViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Login/LoginService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
- 로그인 api 수정
- JWT Token Authrization 헤더 담아줌
- 이메일 인증 발송 버튼 터치 시 현재 디바이스 정보를 같이 담아 보냄
- Error 분기 처리 
- 백업 패스워드 작성 뷰, 뷰모델 개발
> [iOS] Login API 수정

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Model/DDISUser.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/NetworkResult.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/User/UserNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingNetworkResult.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+Backup.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+Email.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+MultiDevice.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/SettingServicaeble.swift
- 세팅 뷰 네트워크 연결
- device와 devices 구분
- 세팅 뷰 네트워크 에러타입 추가
- Refresh 추가
> [iOS] Setting API 수정

- WEB/BE/controllers/iOS/user/index.js
- WEB/BE/models/iOS/DEVICES.js
- WEB/BE/routes/iOS/user/index.js
- iOS device model 수정
- swagger 수정
- getUser 응답 형식 변경
> [BE] iOS API, Model 수정

- WEB/BE/utils/crypto/index.js
- WEB/BE/utils/totp/hmac.js
- WEB/BE/utils/totp/index.js
- hmac 유틸함수 리팩토링
- hmac 유틸함수 적용
- totp 생성
- encryptWithSHA256
> [BE] HMAC 리팩토링 및 적용

- WEB/BE/app.js
- WEB/BE/package-lock.json
- WEB/BE/package.json
- Express에 Helemt을 적용하였습니다.
- XSS 취약성을 보완하기 위해서 추가적으로  적용한 미들웨어
- CSP : Content-Security-Policy 헤더 설정. XSS(Cross-site scripting) 공격 및 기타 교차 사이트 인젝션 예방. 
- xssFilter : X-XSS-Protection 설정. 대부분의 최신 웹 브라우저에서 XSS(Cross-site scripting) 필터를 사용
- Helmet 관련 내용은 기술문서에 간단하게 설명이랑 사용법 올려놓겠습니다.
- close #278
> [BE] Helmet 적용

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Common/AppDelegate.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Common/TokenCryptoManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Model/DDISUser.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/Usecase/MainNetworkResult.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/MainViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/MockTokenService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenServiceable.swift
> [iOS] token refresh

- WEB/BE/controllers/web/auth/index.js
- WEB/BE/controllers/web/user/index.js
- WEB/BE/middlewares/verifyJWT.js
- WEB/BE/models/WEB/AUTHS.js
- WEB/BE/routes/iOS/token/index.js
- WEB/BE/services/web/auth/index.js
- login_fail_count 칼럼 추가
- 관련 필요 API 추가
- 트랜젝션 예방
- 디비 때문에 변경사항이 많습니다 더하여 로그인 관련 전부 좀 건든거 같아서 꼼꼼한 확인 부탁드립니다.. ㅠㅠ
- close #308
> [BE] TOTP TOTP 5번 이상 미일치시 제한

- WEB/FE/src/components/LogIn/LogInContainer.tsx
- 로그인 5회 실패시 다시 로그인 및 Email 전송 알림
- alert 로 알려주고 그냥 리로드
- close #310
> [FE] 로그인 5회 실패시 다시 로그인 및 Email 전송 알림

- WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
- WEB/FE/src/pages/QRCodePage.tsx
- QRCode 컴포넌트 Wapper 변경, 배경색상 변경
- 헤더와 풋터 추가
- close #273
> [FE] QRCode Page Refactoring

- iOS/DaDaIkSeon/DaDaIkSeon/Common/TOTPTimer.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Model/Token.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/Requestable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenEndpoint.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/ViewModel/BackupPaswordViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/Usecase/MainNetworkResult.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/Usecase/MainUsecase.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/CellHandler.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/CheckBoxHandler.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/MainViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/ViewModel/TokenEditViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/MockTokenService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenServiceable.swift
> [iOS] 토큰 서비스 싱크 맞추기 추가

- iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Model/Token.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/Usecase/BackupPasswordUsecase.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/View/BackupPasswordView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/ViewModel/BackupPaswordViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/MockTokenService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenServiceable.swift
- BackupPasswordView state에 따른 변경
> [iOS] BackupPasswordView state에 따른 변경

- iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/ViewModel/BackupPaswordViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
- 복호화 시 비밀 번호가 맞지 않으면 비밀 번호 재설정할 때 버튼 안눌린 현상 해결 
- 메인 뷰 표시 해결
> [iOS] 백업 서버에서 불러온 데이터 복호화(와 이게 되네요..!)

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Date+.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
- zerotoken 문제 해결
- date to string 추가
- settingview device 삭제 문제 해결
> [iOS] Feat/setting network2

- WEB/FE/package-lock.json
- WEB/FE/package.json
- WEB/FE/src/components/ChangePass/ChangePasswordComponent.tsx
- WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
- WEB/FE/src/components/StudyComponent/StudyBox/StudyBox.tsx
- WEB/FE/src/components/StudyComponent/StudyComponent.tsx
- WEB/FE/src/components/findID/findIDComponent.tsx
- WEB/FE/src/utils/message.ts
- 아이디찾기 이메일 전송 성공 알림 추가
- 비밀번호 변경 성공 알림 추가
- 회원가입 시 이메일 인증 알림 추가
- Study Page key warning 해결
- ChangePassword Component 타입에러 해결
- close #341
> [FE,BE] Alert Message 추가 및 타입에러, key warning 해결

- WEB/BE/controllers/web/auth/index.js
- WEB/BE/middlewares/verifyJWT.js
- WEB/FE/src/components/LogIn/LogInContainer.tsx
- WEB/FE/src/components/LogIn/LogInForm.tsx
- 401 에서 403으로 변경 403이 더 적절한 코드
> [FE,BE]  Axios Response Interceptor 설정 변경에 따른 상태 코드 변경

- WEB/FE/config/webpack.common.js
- WEB/FE/src/index.tsx
- 빌드 결과물에 favicon.ico 파일 포함되도록 설정
> [FE] dist에 favicon 포함

- WEB/FE/src/components/LogIn/LogInContainer.tsx
- WEB/FE/src/components/TOTPModal/OTPInput.tsx
- WEB/FE/src/components/TOTPModal/TOTPModal.tsx
- TOTPModal 파일에서 OTPInput 컴포넌트 분리
- OTP 입력 시 포커스 스타일 추가
- 엔터 눌러도 submit 되도록 수정
- TOTPModal 닫으면 상태 초기화되도록 수정
> [FE] TOTPModal 관련 버그 수정 및 개선

- iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenEndpoint.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenNetworkManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenServiceable.swift
> [iOS] Token CRUD

- WEB/BE/controllers/web/user/index.js
- WEB/BE/middlewares/index.js
- WEB/BE/middlewares/validator/config.js
- WEB/BE/middlewares/validator/constants.js
- WEB/BE/middlewares/validator/index.js
- WEB/BE/middlewares/validator/validators.js
- WEB/BE/routes/web/auth/index.js
- WEB/BE/routes/web/user/index.js
- 상수들을 constants.js 로 분리
- totp validator 추가
- 적용할 만한 곳에 validator 적용
```node
exports.validateId = (id) =>
!(longerThan(id, PARAMS.ID.MAX_LENGTH) || shorterThan(id, PARAMS.ID.MIN_LENGTH) || hasWhiteSpace(id));
exports.validatePW = (pw) =>
!(
longerThan(pw, PARAMS.PASSWORD.MAX_LENGTH) ||
shorterThan(pw, PARAMS.PASSWORD.MIN_LENGTH) ||
hasWhiteSpace(pw) ||
!hasNumber(pw) ||
!hasAlphabet(pw) ||
!hasSpecialCharacter(pw)
);
```
> [BE] validator 미들웨어 리팩토링 및 적용

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Common/Views/BackgroundView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Model/DDISUser.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenEndpoint.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/HeaderView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/QRGuideView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingViewComponents/SettingViewWrapper.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/View/TokenCellView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/View/TokenEditView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
- 토큰 추가 시 키보드 올라왔을 때 배경 터치하면 바로 메인화면으로 돌아왔던 것 수정
- inactive 갔다 오면 무조건 메인으로 갔던 것 수정
- MainLinkManager를 추가하여 메인 뷰에서 여러 네비게이션 링크를 관리하도록 했습니다. 
- inactive에서 메인뷰를 보호하는 뷰를 루트 뷰로 바꾸던 방식에서 메인뷰를 덮는 방식으로 변경하였습니다.
> [iOS] 화면 버그 수정

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Common/AppDelegate.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Common/DeviceIDManager.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Common/Extensions/Date+.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Model/DDISUser.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Components/Requestable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Network/Token/TokenEndpoint.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/BackupPassword/ViewModel/BackupPaswordViewModel.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Login/View/LoginEmailView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/Usecase/MainNetworkResult.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/Handlerable.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
- 버그 수정
- UUID를 UDID처럼 사용
- 서버와의 시간차 수정
- TokenService 시간, 싱크 맞추기 어느정도 
- 더 해야함.
- 비밀번호 5개이상 입력 제한 추가
- [self]로 되어있는 것 -> [weak self]로 변경
close #367
> [iOS] 각종 버그들 고침

- WEB/BE/controllers/web/auth/index.js
- WEB/BE/controllers/web/user/index.js
- WEB/BE/routes/web/user/index.js
- WEB/BE/utils/emailSender/index.js
- WEB/FE/src/api/index.ts
- WEB/FE/src/components/QRCodeComponent/QRCodeComponent.tsx
- WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx
- 새로운 API 구현 
- QR 생성 정보를 요청을 받아서 처리하게 만듬과 동시에 만료정보를 확인함
- 기존 넘겨주던 URL 변경 
- 기존에 QR 생성정보를 넘겨주었지만 QR 생성에 필요한 정보를 가진 URL 을 넘김
- close #370
> [BE][FE] QR 생성 페이지 설계 변경

- WEB/FE/src/hooks/index.ts
> [FE] 5주차 2차 배포

- WEB/BE/controllers/web/user/index.js
- WEB/FE/src/hooks/useSignUpInput.ts
> [FE] hotfix

- WEB/BE/controllers/web/user/index.js
- WEB/FE/src/hooks/index.ts
- WEB/FE/src/hooks/useSignUpInput.ts
> [BE] hotfix

- iOS/DaDaIkSeon/DaDaIkSeon/Common/Views/BackgroundView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/MainView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/QRGuideView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenEdit/View/TokenEditView.swift
- iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift
- 편집화면 종료 후 타이머 정지 문제 해결
- 처음 화면을 띄웠을 때 inactive 화면 
- 큐알 등록 화면에서 메인화면으로 바로 넘어갔던 현상 수정
> [iOS] hot_fix

- WEB/FE/src/components/StudyComponent/DragAndDrop/Drag.tsx
- WEB/FE/src/hooks/index.ts
- WEB/FE/src/hooks/useTOTPModal.ts
- WEB/FE/static/TOTPFrame.svg
> [BE] 데모를위한 배포

- iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj
- iOS/DaDaIkSeon/DaDaIkSeon/Common/TOTP/TOTPGenerator.swift
- iOS/DaDaIkSeon/Podfile
- iOS/DaDaIkSeon/Podfile.lock
- PodFile에서 SwiftOTP 제거, uninstall
- swiftOTP 잔재 제거
> [iOS] SwiftOTP 의존성 제거
