WEB/FE/src/index.tsx, WEB/FE/tsconfig.json
- 불필요한 셋팅 코드 제거
- index.tsx 코드 재작성 ...... (어디갔지?)
- index.tsx render 코드를 React.StrictMode를 가장 상위 컴포넌트로 설정하고 그 아래 Global Style과 App을 뒀습니다.
- React.StrictMode의 장점
- 안전하지 않은 생명주기를 사용하는 컴포넌트 발견
- 레거시 문자열 ref 사용에 대한 경고
- 권장되지 않는 findDOMNode 사용에 대한 경고
- 예상치 못한 부작용 검사
- 레거시 context API 검사
- close #18
=> [FE] Global Style 적용 Ver.2 

iOS/DaDaIkSeon/DaDaIkSeon.xcodeproj/project.pbxproj, iOS/DaDaIkSeon/DaDaIkSeon/Common/TOTPGenerator.swift, iOS/DaDaIkSeon/DaDaIkSeon/Common/TOTPTimer.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/Model/Token.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainCellView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainCellViewModel.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenViewModel.swift, iOS/DaDaIkSeon/DaDaIkSeonTests/TOTPGenerationTests.swift, iOS/DaDaIkSeon/Podfile, iOS/DaDaIkSeon/Podfile.lock
- TOTPTimer 추가
- TOTPGenerator 추가
- TOTPGenerator 테스트 코드 추가
- SwiftOTP 라이브러리 추가 
- 지금 MainCellViewModel과 TokenViewModel이 매우 겹치는 상황입니다. 프로토콜이나 상위 클래스로 추상화할지 아니면 하나의 구체타입을 만들고 사용하지 않을 수 있는 속성은 옵셔널 처리할지 고민됩니다. 내일 구조 잡으면서 이것도 해결하면 좋을 것 같습니다.
- 현재 TokenViewModel에서 Token 속성을 @Published로 가지고 있습니다. 그런데 Tokens 데이터를 전역으로 관리한다면 이러한 속성이 필요 없어 보입니다. TokenCellView를 띄울 때 전역으로 가지고 있는 Tokens로 부터 필요한 데이터만 받아서 각각 Published 속성으로 할당해주면 될 것 같습니다. 현재 메인 셀 뷰가 그런 형태인데, MainCellViewModel과 TokenViewModel의 중복을 없애면서 token 속성을 가지지 않는 새로운 token cell viewModel을 구성해보면 어떨까 생각해보았습니다. 
- TimeGenerator를 추가했는데, TimeGenerator class를 사용할지 String extension으로 사용할지 고민하다가 기능의 분류가 명확했으면 좋겠다고 생각하여 class로 작성했습니다.
- TimeGenerator 테스트 코드를 추가했는데, 아직 테스트 케이스가 더 필요해 보입니다. 틈틈히 추가하겠습니다.
- TOTP 알고리즘을 직접 구현해보고 싶었는데, 아직 앱에 적용하기에는 이해가 부족합니다. 다음 …
=> [iOS] TOTP generator, Timer 추가

WEB/BE/app.js, WEB/BE/middlewares/csrf.js, WEB/FE/src/api/index.tsx
- csrf.js의 checkHeader 미들웨어 수정
- dev, prod 환경에서 다르게 동작하도록 지정
- 버그 수정
- axios의 default header로 커스텀 헤더 전송하도록 추가
- 개발환경에서도 csrf 헤더는 체크하도록 설정했습니다.
- localhost:8080 이 아니라면 401에러가 반환됩니다.
=> [BE] csrf header 방어 적용

iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/View/MainView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/View/QRGuideView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift
- 큐알 코드 인식에 성공했을 때 편집 화면 표시
- TokenEditView의 종료 방법을 변경하였습니다. 원래 mode 변수를 사용하여 dismiss를 했었습니다. 이제는 rootView로 바로 이동할 수 있게 하기 위해 NavigationFlow라는 environmentObject를 사용하여 isActive 값을 false로 만들어줌으로써 메인 뷰로 바로 이동되도록 변경하였습니다.
=> [iOS] 큐알 코드 인식 성공시 편집 화면 표시

WEB/BE/controllers/user/index.js, WEB/BE/utils/totp/index.js
- 기존에 있던 Totp관련 함수들( makeSecret, makeURL ) 들을 utils/totp 모듈에서 totp를 호출하여 사용할 수 있도록 하였습니다.
- Secret Key를 만들 때 speakeasy API를 사용하였지만, crypto를 사용하여 Secret Key를 만들도록 변경하였고 base32로 인코딩하여 다른 곳들에서 사용이 되도록 하였습니다.
- TOTP 6자리를 검증하는 함수를 미들웨어 사용없이 구현하여 totp에 추가하였습니다.
- 만드는 방식은 wiki 에 정리 하도록 하겠습니다 !
```javascript
const totp = require('@utils/totp');
totp.makeSecretKey(length=20);
totp.makeURL({ secretKey, email });
totp.verifyDigits(key, digits, date= new Date());
```
위와 같이 사용하면 되고 '=' 이 포함되어 있는 것들은 default 값이 있는 것들입니다.
- close #105
=> [BE] 외부 lib없이 TOTP 미들웨어 구현

WEB/FE/src/api/index.tsx, WEB/FE/src/components/LogIn/LogInContainer.tsx, WEB/FE/src/components/LogIn/LogInForm.tsx, WEB/FE/src/components/TOTPModal/TOTPModal.tsx, WEB/FE/src/components/common/Modal.tsx
- 로그인 api를 loginWithPassword, loginWithOTP 2개로 구현
- 성공 시 메인으로 이동
- 실패 시 에러 표시
=> [FE] 로그인 api 응답 처리

WEB/BE/controllers/auth/index.js, WEB/BE/middlewares/verifyJWT.js, WEB/BE/utils/totp/index.js
- Crypto의 경우 결과값을 Buffer로 주기 때문에 Buffer값을 지정된 0 ~ 9, a ~ z 까지의 값으로 변환 시켜주고 Base32로 decode 해주었습니다.
- req.body 에 ID가 없어 에러가 났기 때문에 미들웨어에서 id를 req.body에 추가해줬습니다.
```javascript
makeSecretKey(length = 20) {
const bytes = crypto.randomBytes(length || 32);
const set = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz';
let output = '';
for (let i = 0, l = bytes.length; i < l; i++) {
output += set[Math.floor((bytes[i] / 255.0) * (set.length - 1))];
}
return base32.encode(output).replace(/=/g, '');
},
```
set이라는 지정된 값으로 바뀌도록 변경하였습니다.
- close #25
=> [BE] TOTP 검증 API 수정

iOS/DaDaIkSeon/DaDaIkSeon/Common/TOTPTimer.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView+SubViews.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenEditView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/MainViewModel.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenCellViewModel.swift
- 에딧뷰를 sheet로 열 때 타이머 정지
- 돌아올 때 다시 타이머 실행
- 메인뷰에만 필요한 state는 메인뷰일때에만 update하도록 변경
- 남은 초 표시할때 0부터 시작하도록 변경
- 타이머 정지를 위해 cellviemodel에서 타이머를 subscribe하는 클로저를 TOTPTimer에 넘겨줍니다. TOTPTimer는 TokenID를 key로 사용하는 딕셔너리에 해당 클로저를 저장합니다. 클로저를 넘겨줄 때 key는 커링을 사용하여 cellViewModel이 property로 key값을 가지고 있지 않도록 해주었습니다.
- 화면 전환이 시작되면 TOTPTImer의 cancel함수를 호출해줍니다. 이 함수에서는 timer의 upstream을 cancel해줍니다. 
- 모든 타이머가 정지 되었기 때문에 다시 메인 화면에 돌아올 때 모든 셀을 다시 타이머에 등록해주어야 합니다. 이를 위해 TOTPTImer가 startAll함수에서 가지고있는 클로저의 원소들을 돌면서 실행해줍니다.
- 셀을 삭제할 때 타이머에 있는 클로저 삭제를 위해 메인 뷰모델에서 타이머의 deleteSubscribers를 호출해줍니다.
=> [iOS] 타이머로 인한 에딧뷰 무한 init 문제 해결

iOS/DaDaIkSeon/DaDaIkSeon/Main/View/SearchBarView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/ViewModel/TokenCellViewModel.swift
- search 중 cell로 돌아갔을 때 TextField 버그 수정
- endSearch 할 때 무조건 freshSearchBar() 불리게 변경  
- `self` -> self수정
=> [iOS] search 중 cell로 돌아갔을 때 TextField 버그 수정

iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/Services/TokenService.swift, iOS/DaDaIkSeon/DaDaIkSeon/Main/View/TokenCellView.swift
- Service 키체인 불러오기 버그 수정
- 조금 생각해볼 애니메이션 추가
- 키체인으로 불러왔을 때 isMain에 true가 하나도 없으면 첫번째 token을 메인으로 지정해주었습니다.
- 선택모드 버튼을 누를 때 애니메이션을 추가했습니다. 그런데 생각해보고 고민해보고 다시 한번 생각해볼 필요가 있을 것 같습니다. 
- #52
=> [iOS] Service 키체인 불러오기 버그 수정, 조금 생각해볼 애니메이션 추가

WEB/BE/app.js, WEB/BE/config/swagger.js, WEB/BE/jsconfig.json, WEB/BE/package-lock.json, WEB/BE/package.json, WEB/BE/routes/auth/index.js, package-lock.json
- production 환경에서만 csrf 헤더 체크하도록 수정
- swagger 추가
- yml포맷의 주석을 작성하면 swagger가 api 문서를 생성
- api 문서 작성
- 라우터 파일에 작성
- /api/auth/
- /api/auth/dup-id
- `localhost:3000/api-docs` 로 접속하면 api 문서 조회가능
=> [Common] Swagger 적용 및 api 문서 작성

WEB/FE/src/components/App.tsx, WEB/FE/src/components/LogIn/LogInContainer.tsx, WEB/FE/src/components/LogIn/LogInForm.tsx, WEB/FE/src/components/PrivateRoute/PrivateRoute.tsx, WEB/FE/src/pages/MyPage.tsx
- 로그인페이지에 회원가입, 아이디찾기, 비밀번호 찾기를 추가하였습니다.
- '/' 경로로 이동시에 Mypage로 이동할 수 있도록하였고, 로그인이 되어있지 않다면 로그인을하게 했습니다.
```javascript
const successLoginHandler = () => {
alert(message.SIGNINSUCCESS);
localStorage.user = 'login';
history.replace('/');
};
```
현재 로그인하게되면 localStorage에 'login'값을 저장하여 localStorage.user값이 존재하면 mypage로 바로 넘어가고 아니면 login으로 redirect 하게 하였습니다. user의 값을 의미있는 값으로 전달하고 싶다면 이름이나 아이디를 response로 넘겨받아야할 것 같습니다 !
<br>
<br>
```javascript
function MyPage({}: MyPageProps): JSX.Element {
if (!localStorage.user) {
return <Redirect to='/login' />;
}
return (
<MainPageLayout>
<MyPageContainer />
</MainPageLayout>
);
}
```
redirect관련해서는 react-router v4 이상부터는 history.replace , <Redirect> 를 사용한다는 것을 확인하고 app.js가 지저분해지는 것보다 MyPage 안에서 구분해주는 것이 나을 것 같다는 판단이 들어서 이렇게 구현하였습니다 ! 혹시 문제가 되는 부분이 있으면 알려주시면 …
=> [FE] 로그인페이지, 라우터 변경

WEB/BE/app.js, WEB/BE/middlewares/sessionAuthentication.js, WEB/FE/src/components/MyPage/MyPageContainer.tsx
- BE에서 세션이 없을 때 CSRF Token Cookie를 삭제하도록 하였습니다.
- FE에서 세션이 없어 에러가 발생했을 때 메세지 출력을 변경하고 local Storage를 Clear하도록 하였습니다.
- close #240
=> [FE,BE] 세션 에러처리 수정

WEB/BE/controllers/web/auth/index.js, WEB/BE/routes/web/auth/index.js, WEB/FE/src/api/index.tsx, WEB/FE/src/components/common/Header/Header.tsx
- 로그아웃  요청을하면 서버에서 Session 삭제와 동시에 Cookie를 삭제해줬습니다.
- 로그아웃 요청을 처리한 후에 Local Storage를 삭제하고 페이지를 reload하게 하였습니다.
```javascript
req.session.destroy((err) => {
if (err) next(createError(err));
res.clearCookie('csrfToken');
res.clearCookie('connect.sid');
res.json({ result: true });
});
```
destroy는 비동기 함수이기 때문에 res.json or res.send 코드가 밖에 있으면
```
[ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```
에러를 발생시키니 주의..!
- close #248
=> [FE,BE]로그아웃 (세션, 쿠키, Local Storage) 삭제 구현

iOS/DaDaIkSeon/DaDaIkSeon/Common/DaDaIkSeonApp.swift, iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/View/MainView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Scene/Main/ViewModel/MainViewModel.swift, iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/PinCodeView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Scene/TokenCell/View/TokenCellView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
- inactive 상태일 때 바로 생체인증 적용 모드로 변경
- 취소 버튼 수정
- 키체인 삭제 안되었던 것 수정
- 메인 뷰모델을 @StateObject로 바꿔주었더니 해결되었습니다. 알아보니, StateObject는 원천 데이터라서 뷰가 새롭게 갱신 될 때 다시 생성되지 않는다고 합니다. 하지만 ObservableObject는 새롭게 생성된다고 합니다. 이러한 이슈 때문에 뷰가 갱신되면서 뷰모델도 새롭게 갱신되고, 이 때 이상한 셀이 주입된 것 같습니다. 
- 그래서 다른 원천 데이터도 ObservedObject로 바꾸려고 했습니다. TokenCellViewModel을 바꿨는데, 이번엔 또 메인 셀 뷰가 이상하게 표시 되었습니다. 그래서 다시 ObservedObject로 바꾸어주었습니다. 
- 토큰 삭제할 때, 메인 셀 재지정을 위한 로직에서, 토큰 개수가 0개면 return하는 코드가 있었습니다. 그런데 키체인 삭제 코드를 이 밑에 놓아서 마지막 토큰을 삭제할 때 키체인에 반영되지 않았었습니다. 그래서 위 쪽으로 옮겨주었습니다. 
- App Struct에서 로그인 화면, 메인화면, 핀코드 화면을 나눠주는 enum 타입을 만들어주었습니다. 이 값을 State로 선언하여, 변경되면 해당 뷰로 이동하도록 했습니다. 
- close #285
=> [iOS] 생체인증 완성, 키체인 삭제 버그 수정

WEB/BE/controllers/web/auth/index.js, WEB/BE/middlewares/verifyJWT.js, WEB/BE/models/WEB/AUTHS.js, WEB/BE/services/web/auth/index.js
- auth 모델 수정
- last_totp 정보 추가
- 로그인시 last_totp 정보 갱신
- 로그인에 사용된 otp 와 last_totp 정보가 동일할 경우 로그인 못하게 막기
- API 메시지로 '한번 사용된 OTP입니다 다음 OTP 정보를 이용하세요' 넘겨줌
- 모델 변경이기 때문에 배포 서버의 auth 에 last_totp 추가 또는 새로 만들기 필요
- 별다른 옵션은 없으며 타입은 Integer 
- close #305 #306 #309
=> [BE] totp 반복 로그인 제한

WEB/BE/middlewares/sessionAuthentication.js, WEB/FE/src/api/config.ts, WEB/FE/src/api/index.ts
- Axios Inceptions 설정
- params 의 값으로 CSRF Token Cookie 값을 설정해줬습니다.(로그인하기 전에는 undefine값을 갖고있습니다)
- Axios 적용
- SessionAuthentication 미들웨어 안에서 세션을 체크할 때 query로 들어온 csrf token값과 세션에 존재하는 csrf token을 비교하였습니다.
```javascript
sessionCheck(req, res, next) {
const { CSRF_TOKEN } = req.session;
const { csrfToken } = req.query;
if (!req.session.user && CSRF_TOKEN !== csrfToken) {
res.clearCookie('csrfToken');
return next(createError(401, '로그아웃되어 권한이 없습니다.'));
}
....
}
```
- close #331
=> [FE] Axios Interceptor 설정 및 SessionAuthentication 리팩토링

iOS/DaDaIkSeon/DaDaIkSeon/Model/Token.swift, iOS/DaDaIkSeon/DaDaIkSeon/Network/Setting/SettingNetworkManager.swift, iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingNetworkResult.swift, iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/Usecase/SettingUsecase.swift, iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/View/SettingView.swift, iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+Email.swift, iOS/DaDaIkSeon/DaDaIkSeon/Scene/Setting/ViewModel/SettingViewModel+MultiDevice.swift, iOS/DaDaIkSeon/DaDaIkSeon/Services/SettingService/MockSettingService.swift, iOS/DaDaIkSeon/DaDaIkSeon/Services/Token/TokenService.swift
- 완전히 네트워크 처리가 되었을 때에만 UI 변경되도록 변경
- 세팅뷰 모든 네트워크 연결 완료
- 아직 세팅뷰에서 변경사항이 생길 때 유저 디폴트로 저장해주는 작업을 하지 못했습니다. 지금은 네트워크가 잘 연결되어 괜찮짐만, 네트워크가 연결되지 않은 상태에 있을 때 유저 디폴트에 있는 값을 띄워줘야 합니다. 이 값이 항상 네트워크와 연결되어 있었던 최신의 상태를 가지도록, 변경사항이 있을 때 마다 유저 디폴트에도 저장해주어야 합니다. -> 이건 토큰에서도 마찬가지!
- 아직 이메일 변경이 되었다 안되었다 하는데, 정확한 이유는 내일 백엔드 팀원들과 이야기해보아야 합니다.
=> [iOS] SettingView 네트워크 정리 

WEB/FE/src/api/config.ts, WEB/FE/src/components/MyPage/MyPageContainer.tsx
-  Local Storage 삭제
-  Page Reload
```javascript
Axios.interceptors.response.use(
(response) => response,
(error) => {
alert(`${error.response?.data?.message || error.message}`);
if (error.response.status === 401) {
storageHandler.clear();
window.location.reload();
}
return Promise.reject(error);
},
);
```
고민했던 부분은 MyPage에서는 401 Error에 대한 처리로 Local Storage를 삭제해주고 alert로 권한이 없음을 알려주고 있었는데 interceptor를 설정하면서 그부분이 필요없어졌습니다. 그래서 모든 에러의 알림을 interceptor에서 띄워주기로 결정하였습니다. 또한 에러에 대한 추가적인 조치나 작업이 필요하다면 그 때 컴포넌트에서 catch로 잡아서 에러를 처리해주면 좋을 것 같다는 판단을 내려 MyPage에 있던 catch는 제거했습니다 !
- close #343
=> [FE] Axios Response Interceptor 설정

WEB/BE/controllers/web/auth/index.js, WEB/BE/controllers/web/user/index.js, WEB/BE/middlewares/verifyJWT.js, WEB/FE/src/api/config.ts, WEB/FE/src/components/FindPassword/FindPasswordForm.tsx, WEB/FE/src/components/LogIn/LogInForm.tsx, WEB/FE/src/components/findID/findIDComponent.tsx
- Modal에 띄워지는 에러들(TOTP번호실패, 한번사용된 TOTP, 비밀번호틀림(MyPage에서 내정보 수정할 때))을 400번대(Client 오류)의 488 에러코드(존재하지않음)를 할당하여 따로 필터해줬습니다.
- 403 에러같은 경우 사용자가 컴포넌트 내부적으로 alert처리 후 추가적인 작업이 있기 때문에 Interceptor에서 alert를 띄우지않도록 필터해줬습니다.
- 400에러를 띄워주는 것들(아이디,비밀번호 틀림 등)이 현재 컴포넌트 내부적으로는 catch로 잡아서 alert만 띄워주고 있기 때문에 불필요한 catch를 제거하여 alert의 중복을 줄였습니다.
```javascript
//verifyJWT.js
...
if (String(lastOtp) === digits)
return next(createError(488, '한번 사용된 OTP입니다 다음 OTP 정보를 이용하세요'));
if (!(await checkLoingCount(id, next))) return;
const secretKey = (await authService.getAuthById({ id })).secret_key;
const result = totp.verifyDigits(secretKey, digits);
if (!result) {
await authService.loginFail({ id });
return next(createError(488, 'TOTP 6자리가 틀렸습니다.'));
}
```
- close #359
=> [FE,BE] 에러코드 변경 및 에러코드에 따른 Alert 필터

WEB/FE/src/api/index.ts, WEB/FE/src/components/FindPassword/FindPasswordContainer.tsx, WEB/FE/src/components/LogIn/LogInContainer.tsx, WEB/FE/src/components/TOTPModal/TOTPModal.tsx, WEB/FE/src/hooks/useTOTPModal.ts
- TOTPModal을 사용할 때 공통적으로 사용되는 부분을 커스텀 훅으로 추가
- LogInContainer, FindPasswordContainer에 적용
```javascript
const submitHandler = (reCaptchaToken: string) =>
findPasswordWithOTP({ authToken, totp: TOTP, reCaptchaToken }).then(() => findPasswordSuccess());
const reIssueHandler = (reCaptchaToken: string) =>
sendSecretKeyEmail({ authToken, reCaptchaToken }).then(() => alert(message.EMAILSECRETKEYSUCCESS));
const {
isModalOpen,
openModal,
closeModal,
TOTP,
setTOTP,
hasTOTPModalError,
modalDisabled,
errorMsg,
onReIssueQRCode,
onSubmitOTP,
} = useTOTPModal({ reIssueHandler, submitHandler });
```
=> [FE] useTOTPModal 구현

WEB/FE/src/api/index.ts, WEB/FE/src/components/ChangePass/ChangePasswordComponent.tsx, WEB/FE/src/components/SignUpComponent/SignUpComponent.tsx, WEB/FE/src/components/findID/findIDComponent.tsx, WEB/FE/src/hooks/index.ts, WEB/FE/src/hooks/useEmailInput.ts, WEB/FE/src/hooks/usePasswordInput.ts, WEB/FE/src/hooks/useSignUpInput.ts
- useEmailInput Hook 구현 및 적용
- usePasswordInput Hook 구현 및 적용
- useSignUpInput 구현 및 적용
반복해서 사용된 컴포넌트들 중에 상태만을 사용하는 컴포넌트( DefaultInput, PhoneInput)을 제외하고, 상태 + 이벤트 핸들러 + onChange에 추가적인 작업이 필요한 것들만 custom Hook으로 만들어줬습니다.
```javascript
const makeOnChange = (setFunc: React.Dispatch<React.SetStateAction<string>>, isPassword: boolean) => {
return (e: React.ChangeEvent<HTMLInputElement>) => {
setFunc(e.target.value);
const comparePassword = isPassword ? rePassword : password;
if (e.target.value !== comparePassword) setAccord(false);
else setAccord(true);
};
};
const onChangePassword = makeOnChange(setPassword, true);
const onChangeRePassword = makeOnChange(setRePassword, false);
```
만들면서 반복되는 함수들은 클로저를 활용해서 코드를 줄여봤습니다 !
- close #362
=> [FE] useEmailInput, usePasswordInput, useSignUpInput 구현

WEB/BE/controllers/web/user/index.js, WEB/FE/src/api/index.ts, WEB/FE/src/components/MyPage/MyPageContainer.tsx, WEB/FE/src/components/StudyComponent/StudyComponent.tsx, WEB/FE/src/types/apiType.ts
- API Generic Type지정
- 타입 types 폴더에 따로 빼놓기
- API.ts 폴더에 타입값들이 너무 많아져서 보기 싫은 것 같으면 
```javascript
import * as types from '@types/apiType.ts';
```
이렇게 수정해도 될 것 같습니다 !
그리고 @types 를 경로로 사용하면 문제가 발생하는데 다른분들도 문제가 발생하는지 한번 확인 가능할까요?!
제가 이전에 types가 어떤 것과 겹치는 느낌이어서 type으로 바꿨던 것 같은데 다시 types로 바뀌었네요 ㅎㅎ
- close #368
=> [FE] API Generic Type지정 및 파일 분리

WEB/BE/middlewares/sessionAuthentication.js, WEB/BE/routes/web/user/index.js
- api/user/update (Method: POST) 라우터 추가
- patch Method를 form tag로 전달할 수가 없다.........
- session authentication에서 CSRF Token 검사하는 부분을 따로 나눠줘서 '잘못된 접근입니다' 라는 메세지를 띄우게 하였습니다.
- 기존 api/user/ (Method:Patch)에 맞는 body값들을 전달하기 위한 form, hidden Input, button tag를 사용한 CSRF 이메일 템플릿 생성
```javascript
if (CSRF_TOKEN !== csrfToken) return next(createError(401, '잘못된 접근입니다.'));
```
이부분을 주석처리하면 CSRF 공격 통과
```HTML
<form action="http://localhost:8080/api/user/update" method="post">
<input type="hidden" name="name" value="CSRFAttack">
<input type="hidden" name="email" value="csrf@csrf.csrf">
<input type="hidden" name="birth" value="1944-04-04">
<input type="hidden" name="phone" value="444-4444-4444">
<button type="submit" style="all: unset;cursor:pointer; color: #ffffff; font-size: 18px; background-color: …
```
=> [BE]CSRFF Attack을 위한 수정
